# Generated by Django 4.1.1 on 2022-09-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('codePr', models.AutoField(primary_key=True, serialize=False)),
                ('initial', models.CharField(max_length=10)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('idThread', models.AutoField(primary_key=True, serialize=False)),
                ('nomThread', models.TextField()),
                ('projetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Histo',
            fields=[
                ('idHisto', models.AutoField(primary_key=True, serialize=False)),
                ('dateRel', models.DateField()),
                ('nbThreadsRel', models.BigIntegerField()),
                ('nbCommRel', models.BigIntegerField()),
                ('status', models.BooleanField()),
                ('projetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('threadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.threads')),
            ],
        ),
    ]
