# Generated by Django 4.1.1 on 2022-09-28 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.TextField()),
                ('projetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projet')),
            ],
        ),
    ]
